### ISSUE TITLE
请教如何生成如下格式会议文献

### ISSUE THREAD

**Issue by ringsaturn** [CTeX-org/gbt7714-bibtex-style#35]
抱歉打扰，

所在学校使用的文献标准依旧是 1987 年标准

其中对会议中的论文有如下格式的要求：

```
[序号]作者.论文题目[A]//主编.论文集名[C].出版地：出版者，出版年，起-止页码.
```

为了解决这个问题，我把 [dtx 文件的 2998 行](https://github.com/CTeX-org/gbt7714-bibtex-style/blob/141553690407c1fdea2de2912428a56905fa6318/gbt7714.dtx#L2998) 改为了如下样式以满足 `论文题目[A]` 这个排版样式：

```dtx
FUNCTION {inproceedings}
{ "A" set.entry.mark
  incollection
}
```

想知道如何制作 `论文集名[C].` 这个样式？

**Comment by zepinglee** [comment]
目前 `inproceedings` 函数设置了 `mark` 后直接调用 `incollection`（图书的析出文献）的处理方式，所以你们学校要求的“图书的析出文献”的书名后面是否需要加“[C]”？

**Comment by ringsaturn** [comment]
需要

**Comment by zepinglee** [comment]
嗯，那你直接把 `incollection` 函数的
https://github.com/CTeX-org/gbt7714-bibtex-style/blob/141553690407c1fdea2de2912428a56905fa6318/gbt7714.dtx#L2728

改成
```
format.series.vol.num.booktitle "[C]" * "booktitle" output.check
```

**Comment by ringsaturn** [comment]
感谢，格式正常了！
