### ISSUE TITLE
引用两个连续的参考文献时，出现了引用压缩的问题

### ISSUE THREAD

**Issue by ambulancy** [CTeX-org/gbt7714-bibtex-style#36]
如果引用文献只有两个，且是连续的两个，出现了引用压缩的问题。

例如，引用[6,7]，但显示为[6-7]

**Comment by zepinglee** [comment]
标准是怎么要求的？

**Comment by Baileyswu** [comment]
开发者您好，我也遇到了一样的问题。在用 natbib 的时候，连续两个是不会用 [6-7]，而是用[6,7]；直到有两个以上的时候才会压缩。私以为这样的显示更舒适，请问哪里改呢？

**Comment by zepinglee** [comment]
> 开发者您好，我也遇到了一样的问题。在用 natbib 的时候，连续两个是不会用 [6-7]，而是用[6,7]；直到有两个以上的时候才会压缩。私以为这样的显示更舒适，请问哪里改呢？ @zepinglee

需要调用 gbt7714.sty，相关的设置在这一段。
https://github.com/CTeX-org/gbt7714-bibtex-style/blob/e550ee9ae23745b798c8f1371972aacff7d291ce/gbt7714.sty#L122-L127

**Comment by ambulancy** [comment]
你好，我是题主。        根据开发者的回复，我去查了国标，证明开发者是对的。在连续引用问文献时，应该写成[6-7]。         以上意见仅供参考。-------- 原始邮件 --------发件人： Baileys ***@***.***>日期： 2021年3月12日周五 晚上10:32收件人： CTeX-org/gbt7714-bibtex-style ***@***.***>抄送： ambulancy ***@***.***>, Author ***@***.***>主    题： Re: [CTeX-org/gbt7714-bibtex-style] 引用两个连续的参考文献时，出现了引用压缩的问题 (#36)

开发者您好，我也遇到了一样的问题。在用 natbib 的时候，连续两个是不会用 [6-7]，而是用[6,7]；直到有两个以上的时候才会压缩。私以为这样的显示更舒适，请问哪里改呢？
