### ISSUE TITLE
参考文献格式

### ISSUE THREAD

**Issue by qiuqiula** [CTeX-org/gbt7714-bibtex-style#37]
参考文献想用作者的姓氏排序，但又不想年份直接放在作者后面，该如何自定义格式？
另外，使用authoryear格式后，连号参考文献显示为[1,2]，该怎么调变成[1-2]?

**Comment by zepinglee** [comment]
1. 有一个选项
2. 编号正常情况下就是 1-2，另外authoryear 格式的引用不应该用编号
