### ISSUE TITLE
请问如何去掉“参考文献”这个标题？

### ISSUE THREAD

**Issue by leoppro** [CTeX-org/gbt7714-bibtex-style#38]
我尝试使用\renewcommand\refname{}，虽然“参考文献”标题消失了，但是会空出空间，请问如何解决这个问题？

**Comment by zepinglee** [comment]
这个问题跟 bibtex style 无关，你需要重新定义 thebibliography 环境

**Comment by leoppro** [comment]
ok 感谢，通过你指导的方向找到了方案

https://tex.stackexchange.com/questions/22645/hiding-the-title-of-the-bibliography
