### ISSUE TITLE
可以同时有作者姓名和编号吗？

### ISSUE THREAD

**Issue by wj-c** [CTeX-org/gbt7714-bibtex-style#39]
有引用方法能实现类似于\citeauthor{XXX}\cite{XXX}的引用方式吗？

**Comment by zepinglee** [comment]
可以是可以，但是似乎不太符合 GB/T 7714 的要求

**Comment by zepinglee** [comment]
所以你确定自己修改的样式是没问题的？

**Comment by wj-c** [comment]
其实是想写类似于“某某某发现了...”这样的句式，看了一些使用gbt7714文献要求的学校的学位论文，发现几乎都是\citeauthor{XXX}\cite{XXX}这样的形式

**Comment by zepinglee** [comment]
![Screen Shot 2019-04-08 at 7 38 40 PM](https://user-images.githubusercontent.com/12290822/55721418-ef88d780-5a35-11e9-8d5b-8be4375e3168.png)
这里国标的示例是不加编号的，如果你坚持要加编号，可以在调用宏包时用 authoryear，然后在 `\bibliography` 前切换 `\citestyle{super}`

**Comment by wj-c** [comment]
好的谢谢
