### ISSUE TITLE
title中特定大写字母

### ISSUE THREAD

**Issue by e71828** [CTeX-org/gbt7714-bibtex-style#40]

**Comment by zepinglee** [comment]
？描述清楚问题？

**Comment by e71828** [comment]
book类 tilte里含有缩略语或特定大写称谓，或需要首字母大写的词语。譬如软件名，ANSYS，SolidWorks，MATLAB，APDl

**Comment by zepinglee** [comment]
参考 https://github.com/ustctug/ustcthesis/wiki/常见问题#2-参考文献列表的英文标题为何被转为小写
