### ISSUE TITLE
online等并不在pdf显示链接字段

### ISSUE THREAD

**Issue by hahakid** [CTeX-org/gbt7714-bibtex-style#41]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：super / numbers / authoryear

## 描述问题
online等并不在pdf显示链接字段
应该是由链接字段吧

bib 数据库代码：
```TeX
@online{WPI,
	author =      {WPI},
	title =       {WPI},
	url =         {http://computing.wpi.edu/dataset.html},
	year =2019
}
```

截图：

![微信图片_20190807122616](https://user-images.githubusercontent.com/8140299/62594901-db36e780-b90e-11e9-9333-6e0706686a56.png)

**Comment by zepinglee** [comment]
嗯？啥情况？

**Comment by hahakid** [comment]
@zepinglee 很奇怪 一直没有 改了一下又有了 之前一直用ctex，现在用texstudio不是很习惯。原因未知
