### ISSUE TITLE
对于电子公告（EB类型）的文献，如何隐藏他们的载体类型标识代码？

### ISSUE THREAD

**Issue by ehehela** [CTeX-org/gbt7714-bibtex-style#43]
对于电子公告（EB类型）的文献，如何隐藏他们的载体类型标识代码？

举例：我希望使用下面的效果：
[1] XING M. Online article[EB]. 2019. http://www.example.com.
而不是下面的效果：
[1] XING M. Online article[EB/OL]. 2019. http://www.example.com.

**Comment by zepinglee** [comment]
我刚刚加了一个选项 `show.medium.type`，效果见 https://github.com/CTeX-org/gbt7714-bibtex-style/commit/775608f7d5647ba4378aa43e788746cde67b0b4e#diff-1e9ad3b14f33265b33b0362c7f71a0c1

**Comment by ehehela** [comment]
@zepinglee 感谢帮助，问题已解决。
