### ISSUE TITLE
人名中的西欧字母不能自动大写

### ISSUE THREAD

**Issue by ehehela** [CTeX-org/gbt7714-bibtex-style#44]
在写学位论文的过程中，我发现：外国人名中的西欧字母没有大写。
如用以下条目，那个变音字母\\"{e}就不能自动大写。不过目前可以通过手动输入\\"{E}解决此问题。
```
@article{RN150,
   author = {Dolbow, J. and Mo\"{e}s, N. and Belytschko, T.},
   title = {Discontinuous enrichment in finite elements with a partition of unity method},
   journal = {Finite Elements in Analysis and Design},
   volume = {36},
   number = {3-4},
   pages = {235-260},
   year = {2000},
   type = {Journal Article}
}
```

我这里列了一些变音字母，希望对您有帮助
```\"{a}\"{A}\"{e}\"{E}\"{\i}\"{I}\"{o}\"{O}\"{u}\"{U}\"{y}\"{Y}{\ss}{\SS}\`{a}\`{A}\'{a}\'{A}\^{a}\^{A}\`{e}\`{E}\'{e}\'{E}\^{e}\^{E}\`{\i}\`{I}\'{\i}\'{I}\^{\i}\^{I}\`{o}\`{O}\'{o}\'{O}\^{o}\^{O}\`{u}\`{U}\'{u}\'{U}\^{u}\^{U}```

**Comment by zepinglee** [comment]
按照 btxdoc，`{Mo{\"e}s}` 是可以正确处理的，我稍后再详细研究下。

**Comment by ehehela** [comment]
加括号可以接受，谢谢。
