### ISSUE TITLE
如何调整相邻两个参考文献项目的垂直距离？

### ISSUE THREAD

**Issue by krisfans** [CTeX-org/gbt7714-bibtex-style#46]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：super
## 描述问题
LaTeX的参考文献项目会和正文列表环境的默认设置一样会有一个垂直距离，而我想取消这一垂直距离，但是不知道该怎么做。宏包的说明文档不涉及项目垂直距离的调整。
最小示例
```TeX
\documentclass[a4paper,zihao=-4,UTF8]{ctexart}
\usepackage[left=3.18cm,right=3.18cm,top=2.54cm,bottom=2.54cm]{geometry}%页面设置
\usepackage{tocbibind}
\usepackage[colorlinks]{hyperref}%书签
\usepackage{zhlineskip}%行距
\usepackage{zhlipsum}%中文乱数假文
\usepackage[super]{gbt7714}%参考文献角标数字顺序编码
\pagestyle{plain}
\begin{document}
\zhlipsum[1][name=aspirin]
\nocite{*}
\bibliography{antenna1}%生成参考文献
\end{document}
```
bib 数据库代码：
```TeX
@book{__nodate,
    address = {北京},
    title = {天线原理},
    publisher = {国防工业出版社},
    author = {{魏文元，宫德明，陈必森}}
}

@book{__nodate-1,
    address = {北京},
    edition = {4},
    publisher = {高等教育出版社},
    author = {西安交通大学高等数学教研室},
    title = {复变函数}
}

@book{__nodate-2,
    address = {北京},
    title = {天线原理天线原理天线原理天线原理天线原理天线原理天线原理天线原理},
    publisher = {国防工业出版社},
    author = {{魏文元，宫德明，陈必森}}
}

```

截图：
![参考文献](https://user-images.githubusercontent.com/57793534/71479526-b98fbb80-282f-11ea-9001-e1844589b9bf.png)

**Comment by zepinglee** [comment]
`gbt7714` 是通过 `natbib` 宏包实现的，你说的这个垂直距离似乎是 `\bibhang`（见 `natbib` 宏包的文档）？

另外 `author = {{魏文元，宫德明，陈必森}}` 写成这样会阻止 BibTeX 进行格式的调整，建议参考 BibTeX 文档中的标准写法。

**Comment by krisfans** [comment]
> 
> 
> `gbt7714` 是通过 `natbib` 宏包实现的，你说的这个垂直距离似乎是 `\bibsep`（见 `natbib` 宏包的文档）？
> 
> 另外 `author = {{魏文元，宫德明，陈必森}}` 写成这样会阻止 BibTeX 进行格式的调整，建议参考 BibTeX 文档中的标准写法。

谢谢。项目之间的垂直距离确实可以通过对`natbib`宏包的`\bibsep`赋值实现调整。另外，参考文献的格式我会注意去满足`bibtex`的标准的，问题已解决。
