### ISSUE TITLE
[文档] 统一「不再需要使用 `\bibliography`」中的强调范围

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/gbt7714-bibtex-style#49]
文档中，共有三处提及「不再需要使用 `\bibliography`」，其中两处（使用 `\emph`）强调了 `不再`，一处仅强调了 `不`。建议统一。

https://github.com/CTeX-org/gbt7714-bibtex-style/blob/775608f7d5647ba4378aa43e788746cde67b0b4e/gbt7714.dtx#L171
https://github.com/CTeX-org/gbt7714-bibtex-style/blob/775608f7d5647ba4378aa43e788746cde67b0b4e/gbt7714.dtx#L175
https://github.com/CTeX-org/gbt7714-bibtex-style/blob/775608f7d5647ba4378aa43e788746cde67b0b4e/gbt7714.dtx#L195

**Comment by zepinglee** [comment]
这个“不再需要使用 `\bibliographystyle`”是早期的设计，后来不断有人遇到问题所以加了几次文档反复强调。我现在不太赞成这样设计。

最初我没注意到 `natbib` 的 `\bibliographystyle` 可以同时修改 citation style 的功能（`natbib` 文档第 2.10 节），所以在设计接口时为了简单，直接在宏包选项设置 citation style 时同时设置 bibliography style。这样的后果是，用户如果在文档中使用 `\bibliographystyle` 时会导致 `aux` 文件中多了一个 `\bibstyle` 造成第二遍编译报错。

现在看来，这样跟 LaTeX 原始的接口不一致的设计不太合理。目前考虑跳个大版本：
1. 要求用户使用 `\bibliographystyle` 调用 bst；
2. 两个 bst 文件名改为 `gbt7714-numerical.bst` 和 `gbt7714-author-year.bst`；
3. `gbt7714-numerical.bst` 对应的 citation style 默认使用上标式（`super`），如果需要改为正文式（`numbers`），需要再手动设置 `\citestyle{numbers}`。

**Comment by muzimuzhi** [comment]
> 1. 要求用户使用 `\bibliographystyle` 调用 bst；

挺好

**Comment by DangeRS2** [comment]
一个建议：关于调用bst的实现思路，其实可以借鉴ctex中fontset选项。默认行为与原版本一样，以保证兼容性，后续添加一个none选项，开放用户接口，供高级用户DIY。

**Comment by zepinglee** [comment]
> 一个建议：关于调用bst的实现思路，其实可以借鉴ctex中fontset选项。默认行为与原版本一样，以保证兼容性，后续添加一个none选项，开放用户接口，供高级用户DIY。

其实可以通过修改 `\bibliographystyle` 和 `\bibliography` 实现无缝过渡
