### ISSUE TITLE
当  BIB 的 DOI 字段中含有下划线时编译错误

### ISSUE THREAD

**Issue by GitatHub** [CTeX-org/gbt7714-bibtex-style#52]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：authoryear

## 描述问题
当 bib 文件中的 doi 含有下划线 “_"
编译错误，
`
! Missing $ inserted.
<inserted text>
                $
l.41 ...k DOI: \doi{{10.1007/978-3-319-60051-2_1}}
`

手动将下划线 ”_“ 改成 \textunderscore 编译通过，但是显示不对
显示的结果和这个一样  
https://tex.stackexchange.com/questions/149086/citation-with-doi-that-has-underscore-breaks-functionality-in-bibdesk

bib 数据库代码：
```TeX
@INBOOK{m2018,
       author = {{Malandraki}, Olga E. and {Crosby}, Norma B.},
        title = "{Solar Energetic Particles and Space Weather: Science and Applications}",
    booktitle = {Solar Particle Radiation Storms Forecasting and Analysis},
         year = 2018,
       editor = {{Malandraki}, Olga E. and {Crosby}, Norma B.},
       volume = {444},
       series = {Astrophysics and Space Science Library},
        pages = {1-26},
          doi = {10.1007/978-3-319-60051-2_1},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2018ASSL..444....1M},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

截图：
![image](https://user-images.githubusercontent.com/8266771/76533999-e741e380-64b3-11ea-90d7-ca13a41b22a0.png)

**Comment by GitatHub** [comment]
a workaround is:
https://tex.stackexchange.com/questions/71215/missing-inserted-issue/315666#315666

**Comment by zepinglee** [comment]
ea96714 解决了 doi 含有下划线的问题
