### ISSUE TITLE
想问一下，如何设置，让参考文献列表里 列全所有作者，而不是前三个。

### ISSUE THREAD

**Issue by DRjy** [CTeX-org/gbt7714-bibtex-style#53]
想更改一下最后文末出现的参考文献，每一个文献，都列全作者名字，不是仅仅3个。
另外，如果想列出作者全名，该怎么设置，谢谢了。

**Comment by zepinglee** [comment]
可以将 bst 文件的参数 `max.num.authors` 改成 `#100`，具体见文档最后一节

**Comment by DRjy** [comment]
您好。我想问一下，那如何让每一条文献的作者是全名，而不是缩写呢？谢谢您了！

**Comment by DRjy** [comment]
@zepinglee 就是有的英文作者，姓是全写，名是缩写

**Comment by zepinglee** [comment]
> @zepinglee 就是有的英文作者，姓是全写，名是缩写

GB/T 7714-2015 就是这样要求的呀

**Comment by DRjy** [comment]
>Jiang W, He G, Long T, Guo H, Yin R, Leng W, Liu H, Wang G. Potentiality of using Luojia 1-01 nighttime light imagery to investigate artificial light pollution. Sensors. 2018 Sep;18(9):2900.
>Jiang, W., He, G., Long, T., Guo, H., Yin, R., Leng, W., ... & Wang, G. (2018). Potentiality of using Luojia 1-01 nighttime light imagery to investigate artificial light pollution. Sensors, 18(9), 2900.
>@article{jiang2018potentiality,
  title={Potentiality of using Luojia 1-01 nighttime light imagery to investigate artificial light pollution},
  author={Jiang, Wei and He, Guojin and Long, Tengfei and Guo, Hongxiang and Yin, Ranyu and Leng, Wanchun and Liu, Huichan and Wang, Guizhou},
  journal={Sensors},
  volume={18},
  number={9},
  pages={2900},
  year={2018},
  publisher={Multidisciplinary Digital Publishing Institute}
}

您好。我现在有一条文献。现在想从第一种格式变为第二种格式，想问一下我该如何修改bst文件？
我用的是标准的gbt7741.bst 
`FUNCTION {format.names}
{ 's :=
  #1 'nameptr :=
  s num.names$ 'numnames :=
  numnames 'namesleft :=
    { namesleft #0 > }
    { s nameptr "{ff~}{vv~}{ll}{, jj}" format.name$ 't :=
      nameptr max.num.authors >
        { bbl.et.al
          #1 'namesleft :=
        }
        { t "others" =
            { bbl.et.al }
            { t get.str.lang 'name.lang :=
              name.lang lang.en =
                { t #1 "{vv~}{ll}{~f{~}}" format.name$
                  uppercase.name
                    { "u" change.case$ }
                    'skip$
                  if$
                  t #1 "{, jj}" format.name$ *
                }
                { t #1 "{ll}{ff}" format.name$ }
              if$
            }
          if$
        }
      if$
      nameptr #1 >
        { ", " swap$ * * }
        'skip$
      if$
      nameptr #1 + 'nameptr :=
      namesleft #1 - 'namesleft :=
    }
  while$
}
`
@zepinglee

**Comment by zepinglee** [comment]
这需要改的就比较多了呀，建议你联系下投稿的期刊/会议有没有符合要求的 bst，不建议从 gbt7714-bibtex-style 的 bst 改。

**Comment by DRjy** [comment]
@zepinglee 你好，我想问一下，让参考文献列表每一个文献前面有个[1],这种数字编号，好设置吗

**Comment by zepinglee** [comment]
> @zepinglee 你好，我想问一下，让参考文献列表每一个文献前面有个[1],这种数字编号，好设置吗？正文中的引用仍然是（作者名字，年份）

这个是用 latex 的宏控制的，如果用了 `natbib`，在 `thebibliography` 前将 citation style 设为 `numbers` 或者 `super` 就可以了

**Comment by Explorer-cc** [comment]
> 可以将 bst 文件的参数 `max.num.authors` 改成 `#100`，具体见文档最后一节

Update一下信息：

在 v2.1.9 以及之前的版本，应该更新的键值对已经变为 (See: https://github.com/zepinglee/gbt7714-bibtex-style/releases/tag/v2.1) ：

- `bibliography.et.al.min`
- `bibliography.et.al.use.first`

https://github.com/zepinglee/gbt7714-bibtex-style/blob/62b4288748353d23decb45b27db4ba8a846d328e/gbt7714-numerical.bst#L65-L66

在 #188 的 v.2.2.0 及以后的版本，可以通过键值对设置来控制：

<img width="1045" height="492" alt="Image" src="https://github.com/user-attachments/assets/54eb7eb0-8779-4e2e-9fb7-c45c3eb18173" />
