### ISSUE TITLE
如何使得英文作者的名字只有首字母大写

### ISSUE THREAD

**Issue by BeingMacro** [CTeX-org/gbt7714-bibtex-style#54]
如何将默认的如下格式
![image](https://user-images.githubusercontent.com/29885273/78966960-bcd75a80-7b33-11ea-85e9-e34fd5a501ca.png)
改为
![image](https://user-images.githubusercontent.com/29885273/78966993-cf519400-7b33-11ea-9083-40e091bade16.png)

**Comment by zepinglee** [comment]
`format.names` 有一段处理英文姓名的：
```
                  t #1 "{vv~}{ll}{~f{~}}" format.name$
                  uppercase.name
                    { "u" change.case$ }
                    'skip$
                  if$
                  t #1 "{, jj}" format.name$ *
```
改成
```
t #1 "{f. }{vv~}{ll}{, jj}" format.name$
```

**Comment by BeingMacro** [comment]
> `format.names` 有一段处理英文姓名的：
> 
> ```
>                   t #1 "{vv~}{ll}{~f{~}}" format.name$
>                   uppercase.name
>                     { "u" change.case$ }
>                     'skip$
>                   if$
>                   t #1 "{, jj}" format.name$ *
> ```
> 
> 改成
> 
> ```
> t #1 "{f. }{vv~}{ll}{, jj}" format.name$
> ```

谢谢！我昨天试了一下，把上面uppercase.name的值设为零也可以

**Comment by zepinglee** [comment]
> 谢谢！我昨天试了一下，把上面uppercase.name的值设为零也可以

注意一下姓和名的顺序以及名的缩写点

**Comment by happyTonakai** [comment]
如果只是把作者姓首字母大写，其他均按照 GBT7714 规定的话，貌似直接把
```
                  t #1 "{vv~}{ll}{~f{~}}" format.name$
                  uppercase.name
                    { "u" change.case$ }
                    'skip$
                  if$
                  t #1 "{, jj}" format.name$ *
```
后面 5 行删掉，只保留第一行就可以了

**Comment by zepinglee** [comment]
> 如果只是把作者姓首字母大写，其他均按照 GBT7714 规定的话，貌似直接把
> 
> ```
>                   t #1 "{vv~}{ll}{~f{~}}" format.name$
>                   uppercase.name
>                     { "u" change.case$ }
>                     'skip$
>                   if$
>                   t #1 "{, jj}" format.name$ *
> ```
> 
> 后面 5 行删掉，只保留第一行就可以了

已经提供了 `uppercase.name`，我上面的改法是为了把姓名格式改成他的示例的顺序
