### ISSUE TITLE
有关手册中一个例子的讨论

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/gbt7714-bibtex-style#56]
今天重新读手册，发现了以下一句话：
```
注意名字之间需要额外的空格，比如“张三, 李四”要排在“张三丰”前面。
```
想了好久，最终给了自己一个解释，不知道是否正确，放在这里以供讨论。

这个例子的出现是为了解释 `key` 中额外的空格，而这空格是为了区分人名而做的人工干预。
现在假设有两个条目（其他内容省略）
```
author={张三 and 李四}
key={zhang1 san1  li3 si4}
```
和
```
author={张三丰}
key={zhang1 san1 feng1}
```
若第一个条目中给出了额外的空格（额外空格存在于 `san1` 和 `li3` 之间），那么排版出来的结果是
```
张三, 李四. ...
张三丰. ...
```
若第一个条目中没有给出额外的空格，那么排版出来的结果是
```
张三丰. ...
张三, 李四. ...
```
这显然是错误的，因为它将拼音中的 `f(eng)` 置于 `l(i)` 之前，虽然遵循了拼音排序但是没有能够识别第一位作者的真实姓名（张三，而非张三李）。

大致目前就是这样的理解了。
另外我不清楚拼音排序按照的是哪个表，是英文字母表还是声母表？

**Comment by zepinglee** [comment]
对，差不多就是这个意思。有次在 thuthesis 讨论时顺手加了一句，没写太详细。

**Comment by OsbertWang** [comment]
现在有这样一个问题。使用 jabref 时，这个软件会自动将 `key` 中的多余空格删除，即便我手动添加了额外的空格用以区分不同人名的拼音。不知道将多余空格改为用其他符号（如 `&`）来区分不同的人是否容易办到？

**Comment by zepinglee** [comment]
> 现在有这样一个问题。使用 jabref 时，这个软件会自动将 `key` 中的多余空格删除，即便我手动添加了额外的空格用以区分不同人名的拼音。不知道将多余空格改为用其他符号（如 `&`）来区分不同的人是否容易办到？

可以，“&” 的 ASCII 码 38 小于拉丁字母，所以不会造成排序上的问题。
