### ISSUE TITLE
"等", "版"这些字乱码了

### ISSUE THREAD

**Issue by ehehela** [CTeX-org/gbt7714-bibtex-style#57]
## 编译环境
宏包版本：gbt7714 v2.0.1
标注样式：super, numbers 
文类：\documentclass[zihao=-4,a4paper,linespread=1.5,twoside]{ctexbook}
导言区部分代码：
```
\usepackage[sort&compress]{gbt7714}
\addtolength{\bibsep}{-0.7em} % 设置参考文献条目间距
\newcommand*{\citen}[1]{% 设置非上标形式的参考文献
  \begingroup
    \romannumeral-`\x % remove space at the beginning of \setcitestyle
    \setcitestyle{numbers}%
    \cite{#1}%
  \endgroup
}
```
正文区部分代码：
```
\backmatter
\bibliographystyle{gbt7714-numerical}
\bibliography{thesis_ref}
\addcontentsline{toc}{chapter}{参考文献}
```

## 描述问题
参考文献条目中同时有中英文时，"et, al", "等", "版"这些字会乱码。
我之前用的是1.X版本的，今天升级后发现乱码了。之前一直都是好好的。论文过几天就要交了😂😂

bib 数据库代码：
```
@book{RN277_Deng2009,
   author = {Mark de Berg and Otfried Cheong and Marc van Kreveld and Mark Overmars},
   translator = {邓俊辉},
   title = {计算几何：算法与应用},
   publisher = {清华大学出版社},
   address = {北京},
   year = {2009},
   type = {Book}
}
```

## 截图
![QQ截图20200504191524](https://user-images.githubusercontent.com/56829479/80960611-c9518900-8e3b-11ea-856a-f5117544128b.png)

旧版本编译结果：
![3](https://user-images.githubusercontent.com/56829479/80960813-3107d400-8e3c-11ea-8e52-759aad395d38.png)

**Comment by zepinglee** [comment]
这个 bst 要求使用 utf-8 编码。你查看下生成的 bbl 是什么编码，有没有乱码？

**Comment by ehehela** [comment]
> 
> 
> 这个 bst 要求使用 utf-8 编码。你查看下生成的 bbl 是什么编码，有没有乱码？

bbl 是 UTF-8 编码，bbl 里面的内容也没有乱码，似乎有一些转义符？

这个问题好像只有中文+英文/数字的时候，并且只发生在“等”、“版”之类的地方，纯英文是没有这个现象的。

bbl 文件：
![1](https://user-images.githubusercontent.com/56829479/81297508-ea1d1700-90a5-11ea-80ce-a782f9239511.png)

对应的编译效果：
![2](https://user-images.githubusercontent.com/56829479/81297536-f73a0600-90a5-11ea-9bae-07e29c848214.png)

**Comment by zepinglee** [comment]
那你检查一下 bst 文件里有没有乱码？我这边复现不出你的问题

**Comment by ehehela** [comment]
> 
> 
> 那你检查一下 bst 文件里有没有乱码？我这边复现不出你的问题

bst 文件里面有乱码，看下图。
奇怪了，我这些文件都是通过 MiKTeX Console 更新的，怎么会这样。 😂😂😂
从 git 上下的版本就没有这个问题，谢谢你啦。

![3](https://user-images.githubusercontent.com/56829479/81300975-066f8280-90ab-11ea-9c33-8e3f3d940797.png)

**Comment by zepinglee** [comment]
MiKTeX 的问题，`dtx` 源文件需要用 `xetex` 编译的。

**Comment by ehehela** [comment]
以前我也是在 MiKTeX Console 中更新的，也没出先这种问题，哎，是不是该换 texlive 了

**Comment by zepinglee** [comment]
> 以前我也是在 MiKTeX Console 中更新的，也没出先这种问题，哎，是不是该换 texlive 了

还好，只是他们打包的时候用了 pdftex 不是 xetex。

**Comment by zepinglee** [comment]
我下次提交 CTAN 的时候不提供 dtx 只提交 bst 就好了。
