### ISSUE TITLE
正文引用中，删除作者与“等”之间的空格

### ISSUE THREAD

**Issue by Raychanan** [CTeX-org/gbt7714-bibtex-style#59]
## 编译环境
标注样式：authoryear

## 描述问题
如图所示，正文引用中，是否能删除作者与“等”之间的空格？

截图：
<img width="653" alt="Xnip2020-05-25_19-52-31" src="https://user-images.githubusercontent.com/53246211/82810557-5fb81e00-9ec1-11ea-97ba-d22e2d311762.png">

**Comment by zepinglee** [comment]
<img width="705" alt="Screen Shot 2020-05-25 at 9 23 51 PM" src="https://user-images.githubusercontent.com/12290822/82816641-17532d00-9ece-11ea-8e86-c4d37f5c9540.png">

**Comment by Raychanan** [comment]
请问能忽略标准，纯粹为了美观而实现“不留空隙”吗？

**Comment by zepinglee** [comment]
https://github.com/CTeX-org/gbt7714-bibtex-style/blob/5f464323d2f890fc2466d8c27f8c71b755eb390f/gbt7714-author-year.bst#L143-L148
这里的 `"\ "` 改成 `""`
