### ISSUE TITLE
网址中，斜杠 `/` 后面会多出一个非 `¬` 符号，如图。

### ISSUE THREAD

**Issue by luo-chuan** [CTeX-org/gbt7714-bibtex-style#60]
网址中，斜杠 `/` 后面会多出一个非 `¬` 符号，如图。

截图：
![图片](https://user-images.githubusercontent.com/33930736/83137754-465ede00-a11c-11ea-9d70-ff3e81b34a2e.png)

bib 数据库代码：
```TeX
@Article{sax059,
  author     = {Agrawal, Rakesh and Gehrke, Johannes and Gunopulos, Dimitrios and Raghavan, Prabhakar},
  journal    = {SIGMOD Rec.},
  title      = {Automatic Subspace Clustering of High Dimensional Data for Data Mining Applications},
  year       = {1998},
  issn       = {0163-5808},
  month      = jun,
  number     = {2},
  pages      = {94–105},
  volume     = {27},
  address    = {New York, NY, USA},
  doi        = {10.1145/276305.276314},
  groups     = {第1章绪论},
  issue_date = {June 1998},
  numpages   = {12},
  publisher  = {Association for Computing Machinery},
  url        = {https://doi.org/10.1145/276305.276314},
}
```

设置如下：

```
FUNCTION {load.config}
{
  #1 'uppercase.name :=
  #3 'max.num.authors :=
  #0 'sentence.case.title :=
  #0 'link.title :=
  #1 'title.in.journal :=
  #1 'show.mark :=
  #1 'show.medium.type :=
  #1 'slash.for.extraction :=
  #0 'in.booktitle :=
  #0 'abbreviate.journal :=
  #0 'italic.journal :=
  #0 'bold.journal.volume :=
  #0 'show.missing.address.publisher :=
  #0 'space.before.pages :=
  #0 'only.start.page :=
  #1 'show.url :=
  #0 'show.doi :=
  #0 'show.note :=
  #0 'show.english.translation :=
}
```

**Comment by Liam0205** [comment]
@luo-chuan 我咋感觉这截图不像是 ltx 排版出来的？@zepinglee

**Comment by zepinglee** [comment]
这个截图不是 gbt7714-bibtex-style 生成的

**Comment by luo-chuan** [comment]
> 
> 
> 这个截图不是 gbt7714-bibtex-style 生成的

就是用gbt7714-bibtex-style生成的呀。我就是在这里下载的。

![图片](https://user-images.githubusercontent.com/33930736/83139996-e9652700-a11f-11ea-8f05-5f38b739d4e8.png)

**Comment by Liam0205** [comment]
@luo-chuan 你这个是 Word 生成的……我们控制不了……

**Comment by luo-chuan** [comment]
> 
> 
> @luo-chuan 你这个是 Word 生成的……我们控制不了……

哦哦，这样啊，那只有搜索替换了。感谢回复！

**Comment by zepinglee** [comment]
我不太了解这个 bibtex4word 是咋实现的，GB/T 7714-2015 的姓名格式是“Agrawal R”，而这个姓名却是“R. Agrawal”。

Word 的引用建议用 Zotero 之类软件的 Word 插件来插入参考文献，应该可以选 GB/T 7714-2015 格式。这些是用 CSL 实现的，感觉比 bibtex4word 更香。

**Comment by luo-chuan** [comment]
> 我不太了解这个 bibtex4word 是咋实现的，GB/T 7714-2015 的姓名格式是“Agrawal R”，而这个姓名却是“R. Agrawal”。
> 
> Word 的引用建议用 Zotero 之类软件的 Word 插件来插入参考文献，应该可以选 GB/T 7714-2015 格式。这些是用 CSL 实现的，感觉比 bibtex4word 更香。

作者那里是学校要求这种格式，然后我参考了你的这个建议 https://github.com/CTeX-org/gbt7714-bibtex-style/issues/54#issuecomment-611902101
