### ISSUE TITLE
Missing whitespace after volume

### ISSUE THREAD

**Issue by wenjie2wang** [CTeX-org/gbt7714-bibtex-style#62]
Thanks for the awesome work!

## 编译环境
宏包版本：gbt7714 2020/03/14 v2.0.1
标注样式：authoryear

## 描述问题
卷号之后空格缺失

bib 数据库代码：
```TeX
@Article{3,
  author =       {严阅 and 陈瑜 and 刘可伋 and 罗心悦 and 许伯熹 and 江渝 and
                  程晋},
  title =        {基于一类时滞动力学系统对新型冠状病毒肺炎疫情的建模和预测},
  journal =      {中国科学：数学},
  year =         2020,
  volume =       50,
  pages =        {1--8},
}
```

截图：

![Screenshot from 2020-06-07 17-41-23](https://user-images.githubusercontent.com/11081955/83980757-34342b00-a8e6-11ea-9997-b640c8d4dc41.png)

The expected output was `50: 1-8`.

**Comment by zepinglee** [comment]
<img width="723" alt="Screen Shot 2020-06-08 at 11 53 27" src="https://user-images.githubusercontent.com/12290822/83991222-ace6c600-a97e-11ea-8278-c09d25e40019.png">
标准中关于冒号和页码之间的空格前后不统一（其他标点其实也是），我这里改成统一带空格吧。

**Comment by zepinglee** [comment]
#70 中讨论了冒号后空格的问题，在 Chicago 格式中卷号和页码之间的冒号后不加空格也是有一定道理的。
