### ISSUE TITLE
兼容 biblatex 的一些域

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/gbt7714-bibtex-style#63]
兼容 biblatex 的一些域：
- [x] langid
- [x] journaltitle
- [x] shortjournal
- [x] location

然后应该鼓励用户使用导出为 biblatex 的数据库格式。

**Comment by hushidong** [comment]
这是好事，程序增加一些逻辑，用户可以少些考虑和麻烦。

**Comment by zepinglee** [comment]
主要是 zotero 导出的 biblatex 格式比 bibtex 的好很多

**Comment by hushidong** [comment]
的确，目前用zotero的比较多

**Comment by zepinglee** [comment]
增加：

1. 使用 “/” 表示起止年份；
2. 而卷和期的起止信息允许用“-”分隔。
