### ISSUE TITLE
Dot after abbreviated English first name

### ISSUE THREAD

**Issue by wenjie2wang** [CTeX-org/gbt7714-bibtex-style#64]
Thanks again for your great work!  It is a feature request instead of a bug report.

## 编译环境
宏包版本：gbt7714 v2.0.2 2020/06/08
标注样式：authoryear

## 描述问题
英语文献中作者名缩写后没有保留句号.  虽然这和gbt7714标准中的范例一致, 但这与其他常用的style（例如 chicago style）不一致.  是否可以考虑加上可以保留句号的选项? 

bib 数据库代码：
```TeX
@book{knuth86a,
  author    = {Donald E. Knuth},
  title     = {The {\TeX}book},
  volume    = {A},
  publisher = {Addison-Wesley},
  address   = {Reading, MA, USA},
  year      = {1986},
  series    = {Computers and Typesetting},
}
```

截图：

- Results from using gbt7714:

![Screenshot from 2020-07-09 00-09-08](https://user-images.githubusercontent.com/11081955/86996826-abc1d800-c17a-11ea-8e27-2576226becc8.png)

- Results from using chicago style:

![Screenshot from 2020-07-09 00-10-42](https://user-images.githubusercontent.com/11081955/86996836-af555f00-c17a-11ea-889d-caec31844a03.png)

**Comment by zepinglee** [comment]
有个选项 `period.between.author.year`

**Comment by wenjie2wang** [comment]
Thanks for you immediate reply!  It is good to know such an option.

Setting `  #1 'period.between.author.year :=` gives me

> Knuth D E. 1986. Computers and typesetting: A  the TEXbook. Reading, MA, USA: Addison-Wesley.

While, I am requesting an option to generate one of the following outputs:
> Knuth, D. E., 1986. Computers and typesetting: A  the TEXbook. Reading, MA, USA: Addison-Wesley.

or
 
> Knuth, D., 1986. Computers and typesetting: A  the TEXbook. Reading, MA, USA: Addison-Wesley.

Notice the comma after last name and period after first name (and middle name).

**Comment by zepinglee** [comment]
我刚看错了，这应该修改 `format.name` 函数
https://github.com/CTeX-org/gbt7714-bibtex-style/blob/972c908dea1cc76e9ba340a3e0fca36fc3a87284/gbt7714-author-year.bst#L518

格式是 `"{vv~}{ll}{ f.}"`

**Comment by wenjie2wang** [comment]
Works like a charm!
