### ISSUE TITLE
关于参考文献中的空格

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/gbt7714-bibtex-style#70]
GB/T 7714-2015 中对空格的处理很不严谨，比如第 6 页顶部：
<img width="816" alt="Screen Shot 2020-09-12 at 00 51 43" src="https://user-images.githubusercontent.com/12290822/92952376-709d9700-f492-11ea-9351-d1c854f5cac2.png">
两处冒号后的空格不一致，甚至同一条文献中两处逗号后的空格都不一致。
为了统一处理，我研究了一下英文中的标点符号用法，总结如下：

1. 逗号和句点后的空格显然是必需的。

2. 文献类型标识前后的中括号：比如“Shaking without quaking [J]”中“[J]”是对整个标题的补充说明，应当用空格隔开。如果将“quaking”和“[J]”连起来：“Shaking without quaking[J]”，“quaking[J]”被视为一个单词，这是不合语义的。

3. 文献类型标识和载体类型标识之间的“/”：这里斜线的用法是 https://en.wikipedia.org/wiki/Slash_(punctuation)#Connecting_non-contrasting_items ，前后不带空格。

4. 表示析出文献的“//”：这里的斜线用法比较接近段行 https://en.wikipedia.org/wiki/Slash_(punctuation)#Line_breaks ，应当前后使用空格。

5. 期刊文献的年、卷、期、页码处的空格：在英文中不同的格式的要求有所区别，Chicago 格式规定的冒号用法：
<img width="603" alt="Screen Shot 2020-09-12 at 01 40 43" src="https://user-images.githubusercontent.com/12290822/92956195-0a684280-f499-11ea-8e95-724da237529d.png">

参考文献示例：
<img width="603" alt="Screen Shot 2020-09-12 at 01 40 15" src="https://user-images.githubusercontent.com/12290822/92956267-2ec41f00-f499-11ea-95d1-f2a10a3deb72.png">
其中卷号和期号之间有空格。

<img width="610" alt="Screen Shot 2020-09-12 at 01 39 58" src="https://user-images.githubusercontent.com/12290822/92956370-51563800-f499-11ea-86a6-74039e464b71.png">
期号和页码之间的冒号后带空格。但是如果没有期号，卷号和页码直接相连，之间的冒号后不带空格。这似乎是来源于排版圣经的习惯。

APA 的格式（https://apastyle.apa.org/style-grammar-guidelines/references/examples/journal-article-references ）是：
<img width="876" alt="Screen Shot 2020-09-12 at 01 46 48" src="https://user-images.githubusercontent.com/12290822/92956655-d6415180-f499-11ea-9f27-54dcc0e6bbe5.png">
卷号和期号之间不带空格。

Vancouver 的格式（https://www.nlm.nih.gov/bsd/uniform_requirements.html ）是：
<img width="1285" alt="Screen Shot 2020-09-12 at 01 55 35" src="https://user-images.githubusercontent.com/12290822/92957411-1228e680-f49b-11ea-9012-3a868bb136da.png">
其中的年、卷、期、页码之间均不带空格。

考虑到以上格式适用的领域，我认为遵循 Chicago 的格式最合适。

6. 修改日期和引用日期的括号前后应使用空格，理由同 2.

中文文献中半宽标点的用法，我还没有调查清楚。

**Comment by zepinglee** [comment]
请教一下 @hushidong 和 @buffalo-d 有什么建议？

**Comment by hushidong** [comment]
挺好的，先按你的这个考虑用着看吧，慢慢收集反馈，看效果怎样。

另外就是要讨论一下，[文献类型标识]前面的空格，对于中文情况也是要加么？中文毕竟不同于英文。

**Comment by zepinglee** [comment]
> 挺好的，先按你的这个考虑用着看吧，慢慢收集反馈，看效果怎样。
> 
> 另外就是要讨论一下，[文献类型标识]前面的空格，对于中文情况也是要加么？中文毕竟不同于英文。

中文的文献我还没考虑好，主要是没找到使用半宽标点符号的相关标准

**Comment by zepinglee** [comment]
> 另外有时，我其实喜欢用半个空格，那么看起来像有空格，又像没有，很容易蒙混过关。

对，如果用 xeCJK 的处理的话，“`中文[`”和“`中文 [`”都会插入中西文之间的 1/4 字宽空白，效果是完全一样的。

**Comment by zepinglee** [comment]
之前 https://github.com/ustctug/ustcthesis/issues/267 也讨论过类似的问题

**Comment by buffalo-d** [comment]
个人倾向：
1. 半角冒号后面用空格和后续内容分隔。
2. 期刊类型方括号用半角，前后没有空格。（[ 和 ] 算是分隔符号，不会和单词字母混淆。）

**Comment by zepinglee** [comment]
我发现了 GB/T 7714-2015 的起草人之一的陈浩元老师的一份 PPT，我发个邮件去联系下他。

**Comment by zepinglee** [comment]
另外 https://www.zhihu.com/question/23371611/answer/24696880 也有一些讨论

**Comment by hushidong** [comment]
好的，看看他们制定者的考虑吧。

**Comment by buffalo-d** [comment]
按说国标是解决大家争议的依据。但愿起草老师们能回应大家的疑惑。

**Comment by zepinglee** [comment]
我待会写邮件，顺便 cc 给你们一份

**Comment by zepinglee** [comment]
没有回复，GG。我决定暂且按照这份 slides 中的样式来处理：http://www.cessp.org.cn/uploads/1/file/public/201607/20160705202202_0airiqt165.pdf 。这主要是相比于其他排版的出版物，ppt 生成的 pdf 能比较好地还原空格的细节。总结如下：

1. 逗号和句点后都有空格。
1. 文献类型标识的中括号前无论是西文还是中文都没有空格。
1. 文献类型标识和载体类型标识之间的「/」，前后不带空格。
1. 表示析出文献的「//」前后无论中文西文都没有空格。
1. 期刊文献的卷号和期号之间无空格，页码前的冒号后有空格。
1. 修改日期和引用日期之间：slides 第 78 页 `(2005-07-12) [2011-07-12]` 有空格，但是另外三处无空格。暂且从众处理把。

@hushidong @buffalo-d 感觉你们俩目前的处理没啥问题，所以就关掉这个 issue 吧。

**Comment by hushidong** [comment]
ok，先这样，以后如果标准更明确了再做处理。

**Comment by hushidong** [comment]
这个slide不错呢。

**Comment by zepinglee** [comment]
> 这个slide不错呢。

另外还可以参考 http://bjxb.cessp.org.cn/ch/reader/view_abstract.aspx?file_no=20150411&flag=1 ，他本人也是《编辑学报》的总编，但是一些地方的处理还是很迷

**Comment by buffalo-d** [comment]
> 这个slide不错呢。

+1～

@zepinglee 感谢！尽管细节的有模糊，但这个是我目前看到的对2015标准最全面的解读了。也可以理解，谈新标的优点，缺点么... 等下一代标准再说。

**Comment by zepinglee** [comment]
<img width="639" alt="Screen Shot 2020-12-30 at 16 34 13" src="https://user-images.githubusercontent.com/12290822/103339633-db63f400-4abc-11eb-871f-c9be28841f04.png">
<img width="636" alt="Screen Shot 2020-12-30 at 16 34 30" src="https://user-images.githubusercontent.com/12290822/103339648-e4ed5c00-4abc-11eb-8ab1-797cc98cbb2f.png">

Microsoft Word 对两处缺少空格的地方标为语法错误。

**Comment by buffalo-d** [comment]
> <img alt="Screen Shot 2020-12-30 at 16 34 13" width="639" src="https://user-images.githubusercontent.com/12290822/103339633-db63f400-4abc-11eb-871f-c9be28841f04.png">
> 
> <img alt="Screen Shot 2020-12-30 at 16 34 30" width="636" src="https://user-images.githubusercontent.com/12290822/103339648-e4ed5c00-4abc-11eb-8ab1-797cc98cbb2f.png">
> 
> Microsoft Word 对两处缺少空格的地方标为语法错误。

这是因为 Word 奇怪的语法错误规则。
![image](https://user-images.githubusercontent.com/40965199/103410489-5c4aea80-4ba6-11eb-9936-5afa3a97299e.png)
