### ISSUE TITLE
参考文献末尾的句点如何去掉

### ISSUE THREAD

**Issue by Second222None** [CTeX-org/gbt7714-bibtex-style#73]
有些中文期刊的参考文献末尾不加句点，该如去掉呢？谢谢！

**Comment by zepinglee** [comment]
https://github.com/CTeX-org/gbt7714-bibtex-style/blob/c2fc95fbbf7493407a2844c372fa2f801caefb37/gbt7714-numerical.bst#L316

去掉 `fin.entry` 的 `add.period$`
