### ISSUE TITLE
请问有无保留 gb/t 7714-2005 的格式？

### ISSUE THREAD

**Issue by tanukihee** [CTeX-org/gbt7714-bibtex-style#76]
虽然有 https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style 的 numerical 的格式，但是没有 author-year 格式的 bst……

我看历史版本是有 2005 的接口的，但好像现在没法用了

**Comment by zepinglee** [comment]
在 https://github.com/CTeX-org/gbt7714-bibtex-style/tree/master/variants 。

**Comment by tanukihee** [comment]
谢谢！
