### ISSUE TITLE
参考文献要求 中文条目附加英文，应如何处理？

### ISSUE THREAD

**Issue by MIngPAPA** [CTeX-org/gbt7714-bibtex-style#77]
例如[《航空动力学报》](http://www.jasp.com.cn/jasp_cn/site/menus/20190910144925001?id=20070331170628001&name=%E6%8A%95%E7%A8%BF%E9%A1%BB%E7%9F%A5)
**参考文献为中文期刊发表的文章时，应在该条文献下附相应的英文。**

e.g. 
[14] 程俊华，倪彬，邓宏武，等．高旋转数内冷通道换热实验技术及验证[J].航空动力学报, 2014,29(8):1817-1823.
CHENG Junhua, NI Bin, DENG Hongwu, et al. Experimental technique of heat transfer in rotating channels at high rotation numbers[J]. Journal of Aerospace Power,2014,29(8):1817-1823. (in Chinese)

又譬如[推进技术](http://tjjs.ijournals.cn/tjjs/ch/reader/view_news.aspx?id=20120719154521001)，引用本刊刊出的文献需要加上英文
e.g.
[6] 林峰，徐辉，曹茂国.微型四孔探针技术初步研究[J]. 推进技术，1992，13(4):69-74.(LIN Feng, XU Hui, CAO Mao-guo. Preliminary Investigation on the Technique of Mini-Four-Hole Probe[J]. Journal of Propulsion Technology, 1992, 13(4):69-74.）

**Comment by zepinglee** [comment]
国标里面提到了双语文献：
<img width="772" alt="Screen Shot 2021-03-09 at 16 49 30" src="https://user-images.githubusercontent.com/12290822/110444110-99c47a80-80f7-11eb-9ba0-dcd1d0b73454.png">

但是 BibTeX 不支持这种格式，你可以考虑 https://github.com/hushidong/biblatex-gb7714-2015 。

另外无法同时满足不同期刊的要求，比如在末尾加“(in Chinese)”还是将英文翻译整体加括号。

**Comment by MIngPAPA** [comment]
感谢作者给予的帮助
∠(｀ω´*)敬礼
