### ISSUE TITLE
请问可否将作者名字改成只有首字母大写呢？

### ISSUE THREAD

**Issue by xunshuideyu096** [CTeX-org/gbt7714-bibtex-style#78]

**Comment by zepinglee** [comment]
`#1 'uppercase.name :=` 改成 `#0 'uppercase.name :=`

**Comment by xunshuideyu096** [comment]
感谢@zepinglee 

我尝试了将#1 'uppercase.name := 改成 #0 'uppercase.name :=，并把文件重命名了。在使用的时候可以改变作者姓名，但是参考文献的序号会丢失。

在 @zepinglee 提示下， 我只改变了原文件中的代码，不再重命名文件，再次运行就得到了想要的结果。
