### ISSUE TITLE
\citet 引用同一作者不同文章的上角标号没有压缩

### ISSUE THREAD

**Issue by junjunhencool** [CTeX-org/gbt7714-bibtex-style#80]
## 编译环境
宏包版本：gbt7714 v2.0
标注样式：super

## 描述问题
\citet{wan.w.liu.l.2008,wan.w.xiong.j.2010,wan.w.ren.z.2012}生成的pdf文档中上标号没有压缩

bib 数据库代码：
@article{wan.w.liu.l.2008,
  author        = {Wan, Weixing and Liu, Libo and Pi, X. and Zhang, M.-L. and Ning, B. and Xiong, Jiangang and Ding, F.},
  year          = {2008},
  title         = {Wavenumber-4 patterns of the total electron content over the low latitude ionosphere},
  pages         = {L12104},
  volume        = {35},
  journal       = {Geophysical Research Letters},
  doi           = {10.1029/2008GL033755}
}
@article{wan.w.xiong.j.2010,
  author        = {Wan, Weixing and Xiong, Jiangang and Ren, Zhipeng and Liu, Libo and Zhang, M.-L. and Ding, F. and Ning, B. and Zhao, B. and Yue, X.},
  year          = {2010},
  title         = {Correlation between the ionospheric {WN4} signature and the upper atmospheric {DE3} tide},
  pages         = {A11303},
  volume        = {115},
  journal       = {Journal of Geophysical Research},
  doi           = {10.1029/2010JA015527}
}
@article{wan.w.ren.z.2012,
  author        = {Wan, Weixing and Ren, Zhipeng and Ding, F. and Xiong, Jiangang and Liu, Libo and Ning, B. and Zhao, B. and Li, Guozhu and Zhang, M.-L.},
  year          = {2012},
  title         = {A simulation study for the couplings between DE3 tide and longitudinal WN4 structure in the thermosphere and ionosphere},
  pages         = {52--60},
  volume        = {90-91},
  journal       = {Journal of Atmospheric and Solar-Terrestrial Physics},
  doi           = {10.1016/j.jastp.2012.04.011}
}

截图：
![图片](https://user-images.githubusercontent.com/33713583/114885190-02122480-9e39-11eb-8703-cb28bcee5b6f.png)

**Comment by junjunhencool** [comment]
![图片](https://user-images.githubusercontent.com/33713583/114886570-39350580-9e3a-11eb-960b-f13881d4d832.png)
请问，怎么改成这种形式？

**Comment by junjunhencool** [comment]
@zepinglee

**Comment by zepinglee** [comment]
似乎 `natbib` 原来的 `\citet` 就没有压缩

**Comment by junjunhencool** [comment]
> 
> 
> 似乎 `natbib` 原来的 `\citet` 就没有压缩

 那这个能修改么，特别是跟\cite引用放在很近时，有的压缩，有的不压缩，看着好不协调
@zepinglee

**Comment by zepinglee** [comment]
> > 似乎 `natbib` 原来的 `\citet` 就没有压缩
> 
> 那这个能修改么，特别是跟\cite引用放在很近时，有的压缩，有的不压缩，看着好不协调
> @zepinglee

比较复杂，需要研究一下。

可以写成 `\citeauthor{wan.w.liu.l.2008}\cite{wan.w.liu.l.2008,wan.w.xiong.j.2010,wan.w.ren.z.2012}`

**Comment by junjunhencool** [comment]
> 
> 
> > > 似乎 `natbib` 原来的 `\citet` 就没有压缩
> > 
> > 
> > 那这个能修改么，特别是跟\cite引用放在很近时，有的压缩，有的不压缩，看着好不协调
> > @zepinglee
> 
> 比较复杂，需要研究一下。
> 
> 可以写成 `\citeauthor{wan.w.liu.l.2008}\cite{wan.w.liu.l.2008,wan.w.xiong.j.2010,wan.w.ren.z.2012}`

@zepinglee 
是的，我暂时就这样处理的，但是这种情况比较多的时候，还是挺麻烦的。感谢，先这样，我先close掉了

**Comment by zepinglee** [comment]
参考 <https://tex.stackexchange.com/q/364555/82731>，`natbib` 没有对 `\citet` 进行 `compress`。

`natbib` 内部控制 `\citet` 格式的是 `\NAT@citexnum`，然而这个定义有 80 行。我最近应该修不动这个。
