### ISSUE TITLE
如何支持bib中type类型？

### ISSUE THREAD

**Issue by fu123456** [CTeX-org/gbt7714-bibtex-style#87]
这个package如何支持bib中type类型，比如我想要的一个博士论文的参考文献格式如下：
赵温波. 2003.径向基概率神经网络研究［D］:[博士] .合肥：中国科学技术大学，21-24.
但是默认的类型“[博士]”是没有的，我在bib中添加了“type={博士}”，编译后也
是不行，这个可以通过修改底层文件实现这个功能的吗？

**Comment by sikouhjw** [comment]
https://github.com/CTeX-org/gbt7714-bibtex-style/blob/2cb5f32991bdc10e5499438c81c88111e405291a/gbt7714.dtx#L240

**Comment by fu123456** [comment]
我这个要求有什么临时办法可以解决吗？因为学校的参考文献格式有这个要求。

**Comment by sikouhjw** [comment]
> 赵温波. 2003.径向基概率神经网络研究［D］:[博士] .合肥：中国科学技术大学，21-24.

你这也不是国标啊。
如果要输出 `type`，可以用 `biblatex-gb7714-2015`，用 `biber` 编译。
```tex
\begin{filecontents*}{test.bib}
@phdthesis{test,
  author  = {赵温波},
  title   = {径向基概率神经网络研究},
  school  = {中国科学技术大学},
  year    = {2003},
  type    = {[博士]},
  address = {合肥},
}
\end{filecontents*}
\documentclass{ctexart}
\usepackage[backend=biber,style=gb7714-2015,gbfieldtype=true]{biblatex}
\addbibresource[location=local]{test.bib}
\begin{document}
  \cite{test}
  \printbibliography[heading=bibliography,title=参考文献]
\end{document}
```

**Comment by zepinglee** [comment]
可以修改 `bst`：
```
FUNCTION {mastersthesis}
{ "D]: [硕士" set.entry.mark
  monograph
}

FUNCTION {phdthesis}
{ "D]: [博士" set.entry.mark
  monograph
}
```

不支持 `type` 有几方面原因：国标中的学位论文类型只有 `[D]`，没有必要进行区分；BibTeX 的标准文献类型有 `@mastersthesis` 和 `@phdthesis` 能够区分，没必要使用 `type`；而且 BibTeX 的标准域 `type` 只用于 `@techreport`。

`@thesis` 和 `type` 的控制方式是 `biblatex` 定义的，但是这样控制格式就很不方便，比如 https://github.com/CTeX-org/gbt7714-bibtex-style/issues/87#issuecomment-944859703 的输出结果是“`[D]. [博士].`”。而且没法用同一 `bibi` 适应不同格式，比如有的学校要求的格式是 `[博士学位论文]`。

**Comment by fu123456** [comment]
我想在问下，按照国标，期刊或者会议全名之后，可以在跟着一个简写吗？比如下面这个例子（第一个只是会议的全称，第二个是会议的全称加上简称）。
Greedy Hierarchical Variational Autoencoders for Large-Scale Video Prediction[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2021.
Greedy Hierarchical Variational Autoencoders for Large-Scale Video Prediction[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR). 2021.
这个在一些期刊或者会议上有这种写法。国标也没有明确说第二种写法不合适，我想问你大佬你的看法。带上简称有一个好处，别人可以很快看出来这个期刊或者会议是什么，毕竟
圈内说哪一个会议都是说简称。

**Comment by fu123456** [comment]
@sikouhjw @zepinglee

**Comment by hushidong** [comment]
当然可以的，要强调一些信息显然不影响写参考文献的目的。国标中并不强制要求期刊名或者会议名怎么写。你自己在会议名上加上就行，当然这样会增加一些信息，后面如果哪个格式要求不能加，你自己得去掉。 hzzmail ***@***.*** 签名由 网易邮箱大师 定制 在2021年10月16日 20:22，sikouhjw 写道： 我想在问下，按照国标，期刊或者会议全名之后，可以在跟着一个简写吗？比如下面这个例子（第一个只是会议的全称，第二个是会议的全称加上简称）。 Greedy Hierarchical Variational Autoencoders for Large-Scale Video Prediction[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2021. Greedy Hierarchical Variational Autoencoders for Large-Scale Video Prediction[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR). 2021. 这个在一些期刊或者会议上有这种写法。国标也没有明确说第二种写法不合适，我想问你大佬你的看法。带上简称有一个好处，别人可以很快看出来这个期刊或者会议是什么，毕竟 圈内说哪一个会议都是说简称。 我对参考文献不是很熟悉。 8.2.3 其他题名信息根据信息资源外部特征的具体情况决定取舍。其他题名信息包括副题名，说明题名文字，多卷书的分卷书名、卷次、册次，专利号，报告号，标准号等。 我感觉简称可以放“其他题名”里面。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zepinglee** [comment]
> 我想在问下，按照国标，期刊或者会议全名之后，可以在跟着一个简写吗？

国标中没有具体要求，你可以在 `booktitle` 自由发挥。

**Comment by hushidong** [comment]
用的第二个命令，你直接考示例编译，我给的示例里面都没有test这个文本信息的，你应该编译的不是一个文件。

**Comment by fu123456** [comment]
在国标中，英文姓名是否全部大写还是首字母大写，以及题目中是第一个字母大写，还是随后的每一个实词都大写，这些理论上应该都可以吧？应该没有明确说一定都大写或者怎么样，只不过在国标给定的参考文献样例中，确实是姓名都全部大写，题目只有首字母大写，后面全部都小写了。这个默认的设置有特别的道理吗？

**Comment by hushidong** [comment]
国标是清楚的，按要求写就好了。但更关键的是学校和老师的要求，所以才会有这些选项来实现多样性的调整。

至于道理，其实没什么特别的道理，只能说是习惯，习惯形成以后就变成惯例了。

**Comment by fu123456** [comment]
大佬，你解决了我很多问题，感谢。使用biblatex也基本ok。不过还有一个问题。就是使用biblatex，使用”\printbibliography“这个命令打印出参考文献。我发现论文参考文献
，在每一页底部有空白部分，我看了下，每一条参考文献都是在当前页，不跨页，我想跨页，也就是一个参考文献可以在两页（一部分在上页的底部，一部分在当前页最上边）。这个如何设定呢？

**Comment by hushidong** [comment]
这个问题是tex内部分页机制产生的，有很多因素的影响：页面设置、字体字号、行距、文献条目的间距等等，主要是垂直方向上的尺度问题。只要根据要求设置好字体、行距、间距就行。不需要关注太多。word也是有这种问题的。

你测试一下整个例子可以看到，不是每一页的情况可能都会不同的。
```

\documentclass{ctexart}
\usepackage[backend=biber,style=gb7714-2015,gbfieldtype=true]{biblatex}
\usepackage[showframe,showcrop]{geometry}

\DeclareFieldFormat[thesis]{title}{#1\addcolon\addthinspace}

\renewbibmacro*{maintitle+booktitle}{%
  \usebibmacro{booktitle}\iffieldundef{shortbooktitle}{}{\setunit{\addspace}\printfield{shortbooktitle}}%
  \newunit}

\renewbibmacro*{journal+issuetitle}{\bibpubfont%源来自standard.bbx
  \usebibmacro{journal}\iffieldundef{shortbooktitle}{}{\setunit{\addspace}\printfield{shortbooktitle}}%
  %\setunit*{\addspace}%
  \setunit*{\addcomma\addspace}%修改为增加一个逗号
  \iffieldundef{series}
    {}
    {\newunit
     \printfield{series}%
     \setunit{\addspace}}%
  %\usebibmacro{volume+number+eid}%
  %\setunit{\addspace}%
  \usebibmacro{issue+date}%
  %\setunit{\addcolon\space}%
  \iffieldundef{volume}{}{\setunit{\addcomma\space}}%
  %换成逗号和空格
  \usebibmacro{issue}%
  \usebibmacro{volume+number+eid}%把卷期放到年份后面
  %\newunit
  }


\addbibresource[location=local]{biblatex-examples.bib}
\begin{document}
  \nocite{*}
  \printbibliography[heading=bibliography,title=参考文献]
\end{document} 
```

结果为：
![图片](https://user-images.githubusercontent.com/20421795/137610464-58a8c63d-7257-478f-85f6-b3f75cd09a50.png)

![图片](https://user-images.githubusercontent.com/20421795/137610473-5b6a1fd5-3b19-4d5a-845b-16d63602da9a.png)

**Comment by zepinglee** [comment]
> 大佬，你解决了我很多问题，感谢。使用biblatex也基本ok。不过还有一个问题。就是使用biblatex，使用”\printbibliography“这个命令打印出参考文献。我发现论文参考文献 ，在每一页底部有空白部分，我看了下，每一条参考文献都是在当前页，不跨页，我想跨页，也就是一个参考文献可以在两页（一部分在上页的底部，一部分在当前页最上边）。这个如何设定呢？

这个是 `biblatex.def` 中 `\interlinepenalty`, `\widowpenalty` 和 `\clubpenalty` 三个参数控制的，而且其实这个比较合理，比如清华就要求“每一条文献的内容要尽量写在同一页内；遇有被迫分页的情况，可通过“留白”或微调本页行距的方式尽量将同一条文献内容放在一页。”

另外还可以把 `bibsep` 设成弹性距离。

**Comment by zepinglee** [comment]
> 在国标中，英文姓名是否全部大写还是首字母大写，以及题目中是第一个字母大写，还是随后的每一个实词都大写，这些理论上应该都可以吧？应该没有明确说一定都大写或者怎么样，只不过在国标给定的参考文献样例中，确实是姓名都全部大写，题目只有首字母大写，后面全部都小写了。这个默认的设置有特别的道理吗？

有，主要是参照了 ISO 690。
<img width="720" alt="Screen Shot 2021-10-17 at 13 46 32" src="https://user-images.githubusercontent.com/12290822/137613565-70497b8b-7da6-4b38-a36d-ca89e88678c8.png">

**Comment by sikouhjw** [comment]
> 
> 
> 大佬们，我还有一个问题，比如：现在有一个期刊的参考文献，但是没有卷号，页码信息，但是有doi信息，这个时候按照国标我的参考文献应该是添加上doi信息吗？当然其他的我都统一没有添加doi信息的。

![图片](https://user-images.githubusercontent.com/49770925/137736529-00d2c22a-fa33-41ad-af83-390debadcef3.png)

**Comment by sikouhjw** [comment]
> 
> 
> 参考文献（电子资源），网页的时间和引用的时间在bib文件中如何体现？ 按照这个项目主页，我使用了urldate这个关键字指定引用时间，编译后发现识别不了。那么这个电子资源时间和引用的时间如何在bib文件中通过关键字指定呢？ 两个两个图显示了这两种时间。 ![gbt1](https://user-images.githubusercontent.com/22411577/138389393-e8ea661e-d789-45b5-95e9-5df50a1c8ae0.png) ![gbt2](https://user-images.githubusercontent.com/22411577/138389407-d0bd5557-415d-4a63-b683-eb6b2ffb59da.png)

```tex
\begin{filecontents*}{test.bib}
@article{libingmu2008hanguo,
  author       = {李炳穆},
  title        = {韩国图书馆法},
  journal      = {图书情报工作},
  year         = {2008},
  volume       = {52},
  number       = {6},
  pages        = {6--12},
  urldate      = {2013-10-25},
  url          = {http://www.docin.com/p-400265742.html},
}
@newspaper{yujianbin2013women,
  author       = {余建斌},
  title        = {我们的科技一直在追赶: 访中国工程院院长周济},
  journal      = {人民日报},
  year         = {2013},
  date         = {2013-01-12},
  number       = {2},
  urldate      = {2013-03-20},
  url          = {http://paper.people.com.cn/rmrb/html/2013-01/12/nw.D110000renmrb_20130112_5-02.htm},
}
\end{filecontents*}
\documentclass{ctexart}
\usepackage{gbt7714}
\bibliographystyle{gbt7714-numerical}
\begin{document}
  \nocite{*}
  \bibliography{test.bib}
\end{document}
```
国标中的参考文献，在 https://github.com/CTeX-org/gbt7714-bibtex-style/blob/master/test/testbst/support/standard.bib 都有

**Comment by fu123456** [comment]
![gbt4](https://user-images.githubusercontent.com/22411577/138393447-237823fc-d791-4d59-9c8b-b01e0c717951.png)

**Comment by zepinglee** [comment]
> 如何一个期刊论文引用的话，如何是出版了，就是[J]了，不需要什么网络链接和doi信息了。

已出版的期刊也可以提供 URL 或 DOI。

> 但是如何一个期刊论文只是在网上论文库中有，还没有出版，只有doi号，相当于[J/OL], 这个时候引用这个期刊论文时，引用时间，pdf文件链接以及doi号都要写上是吧

最好有 URL 或 DOI，引用时间可有可无。

> 感觉这个严格说，下面给的参考文献的格式和上面文字描述的格式要求也不是严格对应。

对于期刊这些不是纯网页的文献，引用时间不重要。
